language: ruby
cache: bundler
rvm:
  - "2.2.0"
bundler_args: --without oracle --jobs=3 --retry=3
script: "RAILS_ENV=ci bundle exec rake ci"
branches:
  only:
    - master
    - develop
notifications:
  slack:
    on_success: never
    on_failure: always
jdk:
  - oraclejdk8