language: ruby
cache: bundler
rvm:
  - "2.2.0"
install: RAILS_ENV=test bundle install --jobs=3 --retry=3

script: "RAILS_ENV=test bundle exec rake ci"
branches:
  only:
    - master
    - develop
jdk:
  - oraclejdk8