#
# Postgres database connections
#
default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  
postgres: &postgres
  <<: *default
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *postgres
  database: development
  
test:
  <<: *postgres
  database: test
  
ci:
  adapter: postgresql
  database: travis_ci_test
  
production:
  <<: *postgres
  database: production

qa:
  <<: *postgres
  database: qa

#  
# Oracle database connections
#
oracle: &oracle
  adapter: oracle_enhanced
  username: <%= ENV['LNA_ORACLE_USERNAME'] %>
  password: <%= ENV['LNA_ORACLE_PASSWORD'] %>

oracle_development: &oracle_dev
  <<: *oracle
  database: lib_dev

oracle_test: *oracle_dev
  
oracle_production: &oracle_prod
  <<: *oracle
  database: library

oracle_qa: *oracle_prod
