development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /lna-dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8080/rest
  base_path: /lna-test
#  url: http://localhost:8080/fedora/rest  
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /lna-prod
