development:
  admin:
    - d31309k@dartmouth.edu       # Carla M. Galarza
    - d28584r@dartmouth.edu       # Eric J. Bivona
    - d31157g@dartmouth.edu       # Paul L. Merchant Jr.
  thayer_manager:
    - d31309k@dartmouth.edu
  archivist:
    - archivist1@example.com
test: &test
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com
ci: *test